### ISSUE TITLE
load failed: roms/DFS-2.26.ROM

### ISSUE THREAD

**Issue by popey** [tom-seddon/b2#109]
On my Linux build of b2, it's no longer finding the DFS ROM file. Looks like in the time since I last built it (20200324) a change has been made to roms.cpp with consts for the ROM files.

```
const BeebROM BEEB_ROM_ACORN_DFS={"DFS-2.26.ROM","Acorn 1770 DFS",StandardROM_Acorn1770DFS};
```

The ROM file is inside the package I build, but as `assets/roms/DFS-2.26.rom` - note that Linux has a case sensitive filesystem, so this is likely why it's failing `ROM` vs `rom`. If you develop on Windows, I imagine this isn't an issue?

**Comment by popey** [comment]
Confirmed. I just did a test build with the following one line change and it works fine on Linux.

```
diff --git a/src/b2/roms.cpp b/src/b2/roms.cpp
index ca23a4a..fa7984a 100644
--- a/src/b2/roms.cpp
+++ b/src/b2/roms.cpp
@@ -21,7 +21,7 @@ const BeebROM BEEB_ROM_OS12={"OS12.ROM","OS 1.20",StandardROM_OS12};
 const BeebROM BEEB_ROM_BPLUS_MOS={"B+MOS.ROM","B+ MOS",StandardROM_BPlusMOS};
 
 const BeebROM BEEB_ROM_BASIC2={"BASIC2.ROM","BASIC II",StandardROM_BASIC2};
-const BeebROM BEEB_ROM_ACORN_DFS={"DFS-2.26.ROM","Acorn 1770 DFS",StandardROM_Acorn1770DFS};
+const BeebROM BEEB_ROM_ACORN_DFS={"DFS-2.26.rom","Acorn 1770 DFS",StandardROM_Acorn1770DFS};
 const BeebROM BEEB_ROM_WATFORD_DDFS_DDB2={"DDFS-1.53.rom","Watford DDFS (DDB2)",StandardROM_WatfordDDFS_DDB2};
 const BeebROM BEEB_ROM_WATFORD_DDFS_DDB3={"DDFS-1.54T.rom","Watford DDFS (DDB3)",StandardROM_WatfordDDFS_DDB3};
 const BeebROM BEEB_ROM_OPUS_DDOS={"OPUS-DDOS-3.45.rom","Opus DDOS",StandardROM_OpusDDOS};
```

**Comment by tom-seddon** [comment]
Thanks for the report, and I'll get this fixed up in the next day or two. I normally use OS X, so it's probably not surprising...

I'll have a go at adding a debug build check that the file name capitalization matches when loading any of the files supplied with the emulator.

Thanks,

--Tom

**Comment by tom-seddon** [comment]
Not tested on Linux, but it looks like my check on OS X is doing the right thing. Turns out the B+ MOS had the wrong capitalization too.

Thanks,

--Tom
