### ISSUE TITLE
New Feature: Add ability to double click on an ssd or dsd to boot it

### ISSUE THREAD

**Issue by TobyLobster** [tom-seddon/b2#117]
Add ability to double click on an .ssd or .dsd file in the finder to load b2, mount the disk, and if applicable apply an automatic SHIFT-BREAK to run it. (similar to e.g. beebem)

**Comment by tom-seddon** [comment]
Yes... good idea. There are various command line options that do currently allow you to do this manually when running from the terminal, but it should properly integrate with the Finder out of the box.

Feels like it should reuse an existing instance if there is one, but I'm open to suggestions.

(Maybe a separate issue, but it should also support Windows Explorer similarly as well.)

**Comment by tom-seddon** [comment]
Fixed in https://github.com/tom-seddon/b2/releases/tag/b2-20221229-183226-24c745f
