### ISSUE TITLE
Debugger: Save a region of memory

### ISSUE THREAD

**Issue by TobyLobster** [tom-seddon/b2#120]
Feature request (if not already available): Is it possible to save a region of memory (e.g. save $7C00-$7FFF for MODE 7 screen data) just as raw binary data to the Mac / Windows filing system? (Probably the emulation should be stopped first!)

**Comment by follower** [comment]
While not quite as convenient as something accessible via the GUI, this functionality is available via the HTTP REST API:

 * https://github.com/tom-seddon/b2/blob/master/doc/Debug-version.md#peekwinbegin-addrend-addr-peekwinbegin-addrsize

So you can use a tool like `wget` or `curl` for example to save a range of memory to a file like this:

```
wget 'http://localhost:48075/peek/b2/0x0000/0x4500'
```

**Comment by TobyLobster** [comment]
ooh, that is useful - thank you!

**Comment by tom-seddon** [comment]
Completely forgot about the http option! Thanks for the note :D

An in-GUI option of some kind will still be forthcoming. I've missed this feature a few times myself.

--Tom
