### ISSUE TITLE
Can't remap keys :(

### ISSUE THREAD

**Issue by MeAndMyRhythmbox** [tom-seddon/b2#122]
I'm trying to remap BBC CAPS LOCK and CTRL keys to physical A and S keys, in order to play Thrust comfortably... even the default caps/ctrl keymap doesn't seem to work as intended - my CTRL key still generates BBC CTRL and the left option key (or left alt in Windows) produces no BBC key at all! 

The left option key is detected as a 'pc key' when I try to map keys myself, but will not produce the desired BBC input... Even when I delete any 'PC key' mapped to BBC A and S, typing them on my keyboard still generates BBC A and S keys! Likewise with physical CAPS LOCK and CTRL.

This is driving me nuts, what can I be doing wrong?

I have observed this behaviour with the following systems, running latest and random previous builds:
Apple 2011 MBP 13" OSX 10.13.6
Hackintosh OSX 10.14.6 with Apple Wired UK Keyboard (no numpad)
Windows 10 with same Apple Keyboard

**Comment by tom-seddon** [comment]
Thanks for the report - you're probably not doing anything wrong, and it'll be a bug :( -apologies for the bother.

Work is keeping me busy at the moment, but I'll look at this as soon as I'm able. 

Thanks,

--Tom

**Comment by MeAndMyRhythmbox** [comment]
Thanks for swift response!

B2 is a great piece of work and I’m loving the debug features. Even contemplated trying to hack my own key choices into the game myself, but hopefully the built in mapping is a quicker fix ;)

**Comment by tom-seddon** [comment]
I've tried reproducing this here with [the current latest release](https://github.com/tom-seddon/b2/releases/tag/b2-20200619-234837-69949ae), but I'm not getting any unusual behaviour. The inbuilt caps/ctrl layout behaves as I'd expect, and I had no problems binding PC A to BBC Caps Lock, PC S to BBC Ctrl, and playing Thrust like that.

Tried on OS X 10.14.6 and Windows 10.

What steps are you following, exactly? What I did:

1. select `File` > `Keymap` > `Default (caps/ctrl)`
2. tap Ctrl, note that this toggles the Caps Lock light

Then:

1. Select `Tools` > `Keyboard Layout...`
2. Click `New...`, select `Default`
3. Select new `Default (2)` keymap in the left column
4. Click BBC CAPS LOCK key, remove PC CapsLock binding, press A to add PC A binding
5. Click BBC CTRL key, remove PC Left Ctrl binding, remove PC Right Ctrl binding, press S to add PC S binding
6. Select new keymap with `File` > `Keymap` > `Default (2)`
7. Run Thrust - note that game is playable

--Tom

**Comment by MeAndMyRhythmbox** [comment]
THANK YOU!
**Your thorough response solved my problem :)**

I was doing everything from the tools > keyboard layout panel. It never occurred to me that this would not also select the keymap being used by the emulator. Going to file > keymap and selecting the keymap there worked! 

Seems it was staring me in the face all along, but I had only used the file menu to change disk image ;)

**Comment by tom-seddon** [comment]
That's useful feedback, thanks... I should probably make the keyboard dialog change the selected keymap in the emulator. 

--Tom
