### ISSUE TITLE
65c02 accuracy

### ISSUE THREAD

**Issue by tom-seddon** [tom-seddon/b2#124]
From http://wilsonminesco.com/NMOS-CMOSdif/

> Indexing across a page boundary caused an extra read of an invalid address, which could cause trouble in some hardware.  (CMOS does an extra read of the last instruction byte instead.) 

See also #116, #15

**Comment by tom-seddon-work** [comment]
Regarding BBR/BBS: https://stardot.org.uk/forums/viewtopic.php?f=4&t=20779#p292332 (not present on the Master; present on the coprocessor - https://stardot.org.uk/forums/viewtopic.php?f=4&t=12351&p=165258#p165170)

**Comment by tom-seddon** [comment]
Going to close this on the basis that it's hopefully covered by https://github.com/tom-seddon/b2/issues/212
