### ISSUE TITLE
Column Heading for Memory Debug window

### ISSUE THREAD

**Issue by TobyLobster** [tom-seddon/b2#128]
Each row of the memory debug view shows 16 bytes. I often find myself counting along a row to find the byte I'm interested in. If a header line "0 1 2 3 4 5 6 7 8 9 A B C D E F" was displayed immediately above the table aligned to each column then it would be easier to identify bytes. (Similarly a header above the ASCII part would be nice).

**Comment by tom-seddon** [comment]
Good idea.

**Comment by TobyLobster** [comment]
In a similar vein, it could also show the currently selected address in this window somewhere, updating the address as the selection is changed.
