### ISSUE TITLE
Question: Joystick/Paddle Support

### ISSUE THREAD

**Issue by muckypaws** [tom-seddon/b2#180]
Hello, 

Is Joystick/Paddle emulation supported in B2 on macOS? If so how? I have a joystick attached via bluetooth or USB but isn't recognised by the emulator.

I'm also unable to find an option to select keys for Joystick Emulation hence the question, has this feature been implemented yet?

Thanks :)

**Comment by tom-seddon** [comment]
There isn't any joystick/paddle support currently, I'm afraid, but it is on the to do list: https://github.com/tom-seddon/b2/issues/14

**Comment by muckypaws** [comment]
Thank you Tom.
