### ISSUE TITLE
Sideways RAM

### ISSUE THREAD

**Issue by TobyLobster** [tom-seddon/b2#181]
Is Sideways RAM supported?

**Comment by tom-seddon** [comment]
It is - the default model B configs have 16K sideways RAM in slot 13, the B+128 has it in slots 0/1/12/13, and the Master 128 ones have it in slots 4-7.

You can add more by ticking the ROM slot's RAM tick box in the `Hardware` > `Configs` window.

Let me know if the UI isn't very clear. I hope to do a pass on the documentation at some point this year.

Thanks,

--Tom

**Comment by TobyLobster** [comment]
Nice! I missed that, thanks.
