### ISSUE TITLE
Libretro Port?

### ISSUE THREAD

**Issue by Ploggy** [tom-seddon/b2#186]
Hi, would you be interested in porting your Emulator to Libretro? There currently isn't a Core for the BBC Micro in Retroarch. 
The BBC Micro is a Computer I used alot as a kid in School I'd love to have that running as Core in Retroarch :) 

https://docs.libretro.com/development/cores/developing-cores/

**Comment by SuperBadger77** [comment]
Hi - I would like to 2nd this request. The BBC Micro was an incredible machine that so many of us grew up with. The fact that is missing from RetroArch \ Libretro is a crime. RetroArch now support so many emulators and cores - the fact that the BBC Micro is missing is a glaring omission. Is this something we can interest you in doing / allowing?

**Comment by SuperBadger77** [comment]
@tom-seddon :-)

**Comment by jhob101** [comment]
I would also love to see the BBC in libretro, as @SuperBadger77 says, it does seem like a glaring omission.

**Comment by SuperBadger77** [comment]
I've just been looking at RecallBox for the new Pi Zero 2 image for the GPi Case and realised that they now have BBC Micro support! https://wiki.recalbox.com/en/emulators/computers/bbc-micro/beebem "This core is under GPL license." so there should be no issue adding it to retro arch now @hizzlekizzle 
Details of the add are here: https://gitlab.com/recalbox/recalbox/-/issues/1948

**Comment by tom-seddon** [comment]
I'm not averse to this idea, but I don't think it's something I'd do right now myself. I'll check out retroarch anyway though.

Most of the code in beeb/ could probably be re-used easily enough. It's not intended to be SDL-specific.

--Tom
