### ISSUE TITLE
linux build fails due to libuv test

### ISSUE THREAD

**Issue by mcnalu** [tom-seddon/b2#188]
This may be peculiar to my system by I thought I'd create this issue in case it is of interest to others.

When issuing 'ninja' to build on linux (slackware-current) I got this error:

```
/usr/bin/ld: etc/libuv-cmake/CMakeFiles/run-tests.dir/__/__/submodules/libuv/test/test-poll-closesocket.c.o:/home/nalu/dev/bbc/b2/submodules/libuv/test/test-poll-closesocket.c:29: multiple definition of `handle'; etc/libuv-cmake/CMakeFiles/run-tests.dir/__/__/submodules/libuv/test/test-poll-close-doesnt-corrupt-stack.c.o:/home/nalu/dev/bbc/b2/submodules/libuv/test/test-poll-close-doesnt-corrupt-stack.c:36: first defined here
/usr/bin/ld: etc/libuv-cmake/CMakeFiles/run-tests.dir/__/__/submodules/libuv/test/test-poll-closesocket.c.o:/home/nalu/dev/bbc/b2/submodules/libuv/test/test-poll-closesocket.c:28: multiple definition of `sock'; etc/libuv-cmake/CMakeFiles/run-tests.dir/__/__/submodules/libuv/test/test-poll-close-doesnt-corrupt-stack.c.o:/home/nalu/dev/bbc/b2/submodules/libuv/test/test-poll-close-doesnt-corrupt-stack.c:35: first defined here
collect2: error: ld returned 1 exit status
[418/622] Building CXX object submodules/CMakeFiles/imgui_lib.dir/imgui/imgui.cpp.o
ninja: build stopped: subcommand failed.
```

It didn't look like that these tests seemed all that relevant to b2's use of libuv and since I had a more recent version of libuv installed on my system anyway I worked around this by commenting out these lines in CMakeLists.txt in the root dir of the project:
`
#set(LIBUVDIR ${CMAKE_CURRENT_SOURCE_DIR}/submodules/libuv)
#add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/etc/libuv-cmake)
`

**Comment by tom-seddon** [comment]
https://github.com/libuv/libuv/commit/d42a1085837aecbd2b1e3c2a3a764dba58ad205f

Looks like I need to update the libuv submodule...

There should probably be the option of having it use the system copy anyway by doing find_package.

--Tom

**Comment by tom-seddon** [comment]
This bug will get closed once I've updated the libuv submodule.

I'll open another bug about wider use of `find_package`.

--Tom

**Comment by tom-seddon** [comment]
Fixed... hopefully for good... by 486680c75df68b7700bddc25a1b55b99b51c11cf
