### ISSUE TITLE
error: 'shared_ptr' is not a member of 'std'

### ISSUE THREAD

**Issue by mcnalu** [tom-seddon/b2#201]
Another error in trying to get it built on linux but the good news is this was the last one. B2 is building and running again!

Just one extra include is needed to prevent this error.
```
diff --git a/src/beeb/include/beeb/SaveTrace.h b/src/beeb/include/beeb/SaveTrace.h
index b502c9c..678785e 100644
--- a/src/beeb/include/beeb/SaveTrace.h
+++ b/src/beeb/include/beeb/SaveTrace.h
@@ -14,6 +14,7 @@
 
 #include <thread>
 #include <atomic>
+#include <memory>
 
 class Trace;
```

**Comment by tom-seddon** [comment]
@mcnalu A bunch of this stuff, including the issues you've raised, is (hopefully) now fixed on the `wip/master` branch. I'm not merging it into proper `master` just yet, but that'll probably happen in the next week or two.
