### ISSUE TITLE
Bad dmg in latest release?

### ISSUE THREAD

**Issue by MeAndMyRhythmbox** [tom-seddon/b2#244]
Tested on OSX 10.15.6
b2-osx-20221229-183226-24c745f.dmg is corrupt (even after removing quarentine bit)
Previous release b2-osx-20220803-132314-6a7ed04.dmg opens just fine.

Deleted and downloaded again in a different browser, but still corrupt :(

**Comment by tom-seddon** [comment]
Thanks for the report, and sorry for the bother. I changed the dmg format to ULMO - this is supposed to be compatible with 10.15, but... perhaps it isn't?! I should probably undo this change anyway, as I don't think ULMO is supported by 10.9, which b2 is supposed to work with. I'll do another release in the next week or two.

(As above, the intent is that b2 works with macOS 10.9 - but I have no way of testing this. See https://github.com/tom-seddon/b2/issues/208. Any reports very welcome.)

**Comment by tom-seddon** [comment]
I've put the dmg format back the way it was, and the CI server will produce a new build from it soon! This should be identical to b2-osx-20221229-183226-24c745f, but hopefully with a readable dmg this time!

Please let me know if you have any problems with it.

**Comment by MeAndMyRhythmbox** [comment]
That's great news. Many thanks and happy new year!
