### ISSUE TITLE
Raspberry Pi: Make it compile OOB on AArch64

### ISSUE THREAD

**Issue by egrath** [tom-seddon/b2#265]
**Behavior:**
Does not compile out of the box on Raspberry Pi OS 64-bit because AArch64 isn't handled correctly in the build system

**How to reproduce:**
Install Raspberry Pi Os 64-bit and follow the build instructions, it will fail with some unknown CPU error

**Workaround:**
Tweak the file `shared/h/shared/system.h` by replacing:
```
#elif (defined __arm__)
```
with
```
#elif (defined __arm__ || defined __aarch64__)
```

**Comment by tom-seddon** [comment]
Excellent, thank you. I'll make this change.

**Comment by scruss** [comment]
Can confirm that
`git clone --recursive --branch 'wip/master' https://github.com/tom-seddon/b2.git`
then the usual build process produces a working b2 setup on a 64-bit Raspberry Pi 5
