### ISSUE TITLE
Include registers on disassembly pane

### ISSUE THREAD

**Issue by dave-f** [tom-seddon/b2#27]
Would be very useful to be able to see A,X,Y, SP, PC, and flags in the disassembly pane.

**Comment by tom-seddon** [comment]
There is a debugger pass coming, and I'll add this as part of that!

**Comment by dave-f** [comment]
That’s great, Tom, thanks! I really like the multiple panes and seeing eg the CRTC registers changing as the emulator runs.

With a bit more love on the debugger side of things it’s shaping up to be quite the piece of kit!
