### ISSUE TITLE
Power on Tone Option not being acknowledged

### ISSUE THREAD

**Issue by TheOriginalSR** [tom-seddon/b2#282]
Latest build release - not from source

Tools -> Options
[ ] Power on tone

I may be misunderstanding this, but that would seem to indicate not playing the BBC's Power On tone. 
Regardless of the setting - which is persisted between sessions - the power on tone is still played

This issue was also present in the release around February 2022.

**Comment by tom-seddon** [comment]
Which OS is this? This is supposed to work! Note that this is only intended to affect the lower-pitched 'brrr...' part of the power-on tone. The higher-pitched blip is not silenced.

I'll test the builds in question.

**Comment by TheOriginalSR** [comment]
That was daft if me!

windows build. Running on the latest Windows 11

**Comment by TheOriginalSR** [comment]
Works as expected
