### ISSUE TITLE
Tube ULA not resetting parasite CPU on command

### ISSUE THREAD

**Issue by SamSkivington** [tom-seddon/b2#307]
Wasn't sure whether to add this as an extra for #301, but here goes.

I'm trying to reset the Tube parasite CPU so that my program can read the start-up banner text - an experiment with PiTubeDirect. The code is pulsing bit 5 (P - set parasite reset active low) of &FEE0 high and then low.

I've tried this on a real Beeb and Master (internal and external CoPro both connected) and it works perfectly. In the emulators I've tried...

This is not implemented at all in b2.

Here's the original stardot thread that contains a small BASIC program that can be used to check behaviour:
https://stardot.org.uk/forums/viewtopic.php?t=23211

And here's some Tube ULA reference code that I wrote for jsBeeb:
https://github.com/mattgodbolt/jsbeeb/blob/main/tube.js

**Comment by tom-seddon** [comment]
compat notes on p2 of the thread: https://www.stardot.org.uk/forums/viewtopic.php?t=28163&start=30

**Comment by tom-seddon** [comment]
Fixed by c83c61c0aa794a96af1500339852bec2f3c2f4af
