### ISSUE TITLE
Docs: libglvnd-dev replaces libgles1-mesa-dev

### ISSUE THREAD

**Issue by DaveJeffery** [tom-seddon/b2#31]
Just done an install on Ubuntu 18.04. Worked perfectly but libgles1-mesa-dev seems to have been renamed in Ubuntu as libglvnd-dev, so you might need to update the Linux build instructions.

**Comment by tom-seddon** [comment]
Thanks for the note - will update the docs.

On my todo list is setting up a vagrant VM, so I can be more certain about which dependencies are required...
