### ISSUE TITLE
Start with maximum speed

### ISSUE THREAD

**Issue by TobyLobster** [tom-seddon/b2#388]
Is there a way to start the emulator with the 'Limit Speed' unchecked. I would like to automate running the emulator at maximum speed. I looked in the command line options and the http interface but couldn't find anything.

**Comment by tom-seddon** [comment]
I've added a new command line option, `--no-limit-speed` - please let me know how you get on!

If you don't build from source, there's a new prerelease build coming that will include this.

**Comment by TobyLobster** [comment]
Thanks, I will hold off building from source, but look forward to the prerelease.

**Comment by TobyLobster** [comment]
Just tried it - it works! Thanks for that Tom, appreciate it.
