### ISSUE TITLE
Implement the XDG_DATA_DIRS search for assets

### ISSUE THREAD

**Issue by SteveFosdick** [tom-seddon/b2#5]
On Linux, if I install b2 in a typical executable dir, for example /usr/local/bin it expects to load assets from /usr/local/binb/assets/... which is not normal practice on Linux.  As these are not executable assets whose binary representation would not vary according to the CPU architecture of the machine they would normally go in /usr/local/share/b2...  As b2 uses the XDG specification to locate other files on Linux it should probably use the XDG_DATA_DIRS environment variable which is a colon-separated list of directories to search by appending the application name to each in turn, plus any sub-directorates and the filename under that.  For example:

`/home/user/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/`

**Comment by tom-seddon** [comment]
I'll get this done when I next get some Linux time - this aspect of the Linux build does need a bit of polish.

(It could also do with an install step adding to the cmake project, I think, so this bit is automated. Haven't used this side of cmake yet, but it would be good if there were an equivalent of autoconf's `make install` that could put stuff in `/usr/local/...`, `$HOME/.local/...`, or wherever.)

Thanks,

--Tom

**Comment by tom-seddon** [comment]
`XDG_DATA_DIRS`: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
