### ISSUE TITLE
CMP0004 when building on Ubuntu 18.04

### ISSUE THREAD

**Issue by popey** [tom-seddon/b2#67]
When building b2 in an Ubuntu 18.04 container, I'm getting an error from cmake when building the bundled SDL. 

```
CMake Error at submodules/SDL/CMakeLists.txt:1735 (add_library):
  Target "SDL2-static" links to item "
  -L/build/snapcraft-b2-08cd1e/parts/b2/install/lib
  -L/build/snapcraft-b2-08cd1e/parts/b2/install/usr/lib
  -L/build/snapcraft-b2-08cd1e/parts/b2/install/lib/x86_64-linux-gnu
  -L/build/snapcraft-b2-08cd1e/parts/b2/install/usr/lib/x86_64-linux-gnu
  -L/build/snapcraft-b2-08cd1e/stage/lib
  -L/build/snapcraft-b2-08cd1e/stage/usr/lib
  -L/build/snapcraft-b2-08cd1e/stage/lib/x86_64-linux-gnu
  -L/build/snapcraft-b2-08cd1e/stage/usr/lib/x86_64-linux-gnu" which has
  leading or trailing whitespace.  This is now an error according to policy
  CMP0004.
```

Looks like this was previously a [debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822210;msg=7) fixed in [this commit](https://github.com/tom-seddon/SDL/commit/5790ad40ea27153a056f928b9d779b4d656d1051), but I'm still seeing it. 

Any ideas why?

**Comment by tom-seddon** [comment]
I tried this on my Linux PC, with Ubuntu 18.04 LTS, but it built cleanly... I'm afraid I don't have any current suggestions.

Would it be easy to get myself set up with the same container as you? Then I can have a go at building it myself.

**Comment by tom-seddon** [comment]
Are you still geting this?

Thanks,

--Tom

**Comment by popey** [comment]
No, sorry I should have closed this. If I recall, I just used a newer cmake. Thanks.
