### ISSUE TITLE
NuLA Banding

### ISSUE THREAD

**Issue by SteveFosdick** [tom-seddon/b2#7]
I was just trying the SOTB NuLA demo in b2 and it doesn't look right to me.  Compare the b2 and b-em screen shots.
![2018-04-18-sotb-b-em](https://user-images.githubusercontent.com/1048671/38953267-1b225e46-4346-11e8-8131-5a0b3f8d7056.png)
![2018-04-18-sotb-b2](https://user-images.githubusercontent.com/1048671/38953268-1b62e7f4-4346-11e8-9939-185a8acc2f22.png)

**Comment by elminster** [comment]
I get the same on the Linux ARM and I did in the Linux x86 version but as it is slower I managed to catch it in a screenshot. Something but not as bad as Steve's
![192_168_1_30_5920__bf665efc8444_20__-_vnc_viewer](https://user-images.githubusercontent.com/63932/38961519-d4f4517a-4360-11e8-816d-4016dae1f170.jpg)

**Comment by elminster** [comment]
You probably got it from here 
[](http://stardot.org.uk/forums/viewtopic.php?f=3&t=13545&p=180157&hilit=beast&sid=fd51d1b1f8467c09b9ead2f423ad8b9d#p179195)
that is where I grabbed it from yesterday when I tried it on B-em/B2.

**Comment by tom-seddon** [comment]
Thanks, with that second disc image I'm seeing the palette problem here.

I'm going to open a second bug for the ropey scrolling.

--Tom

**Comment by tom-seddon** [comment]
More colour problems with http://bbcmicro.co.uk/game.php?id=1934.

--Tom

**Comment by tom-seddon** [comment]
Colours are now correct on the SoTB demo, and on Frogger too, I think.

This doesn't fix #8, which remains open.

--Tom
