### ISSUE TITLE
BBC's COPY key unavailable on Mac?

### ISSUE THREAD

**Issue by TobyLobster** [tom-seddon/b2#74]
The Keyboard Layout view (default layout) shows the BBCs COPY key as "PC Keys: Insert", but Macs don't have an insert key. How can I press the equivalent of the BBC's COPY key? Am I missing something obvious?

**Comment by tom-seddon** [comment]
Good question - I use my Macbook with a PC keyboard, and hadn't realised Mac keyboards lack this key! I'm afraid you'll have to create your own mappings and use those - please let me know if the docs aren't clear.

I'll improve the defaults in a future version. Copy will probably be mapped to both End (matching the Archimedes keyboard), and Delete (which is a bit weird, but means it's accessible on a Macbook's onboard keyboard).

Thanks for the report,

--Tom
