### ISSUE TITLE
possible unique_lock errors

### ISSUE THREAD

**Issue by cluder** [tom-seddon/b2#86]
there are several locations where unique_lock<> is used without a variable name.
e.g. `std::unique_lock<Mutex>(m_mutex);` as opposed to `std::unique_lock<Mutex> somelock(m_mutex);`
This might be a problem, as no lock on m_mutex is created.
see this talk https://www.youtube.com/watch?v=lkgszkPnV8g&t=1960

b2/BeebThread.cpp
```
#if BBCMICRO_DEBUGGER
const BBCMicro *BeebThread::LockBeeb(std::unique_lock<Mutex> *lock) const {
    *lock=std::unique_lock<Mutex>(m_mutex);

    return m_thread_state->beeb;
}
#endif
```

**Comment by tom-seddon** [comment]
OK, that's interesting - thank you. The intention here is that the caller provides the lock, that `BeebThread::LockBeeb` actually locks - so the mutex can be private, but the caller can still control the duration of the lock.

I think the code is correct... but that doesn't mean much. I've not noticed any problems from doing it this way... but, ditto! I'll watch the video.

Thanks again,

--Tom

**Comment by tom-seddon** [comment]
These are good (I think) - they're either the RHS of an `=`, or an argument to a function, so always an expression.

Thanks,

--Tom
