### ISSUE TITLE
 error: ‘array’ in namespace ‘std’ does not name a template type in roms.h

### ISSUE THREAD

**Issue by popey** [tom-seddon/b2#99]
I'm building the b2 snap, which builds in an Ubuntu container in launchpad.net (our build farm). Recent (within the last 30 days (can't be more specific, my builds were not being triggered for a separate reason)) it's been failing on roms.h. Here's a snippet.

```
[550/559] Building CXX object src/b2/CMakeFiles/b2.dir/keys.cpp.o
cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++
cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++
[551/559] Building CXX object src/b2/CMakeFiles/b2.dir/roms.cpp.o
FAILED: src/b2/CMakeFiles/b2.dir/roms.cpp.o 
/usr/bin/c++  -DBUILD_TYPE_RelWithDebInfo=1 -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS -DIMGUI_INCLUDE_IMGUI_USER_H -DIMGUI_INCLUDE_IMGUI_USER_INL -DIMGUI_OVERRIDE_DRAWVERT_STRUCT_LAYOUT="struct ImDrawVert {ImVec2 pos; ImU32 col; ImVec2 uv;}" -DNO_IMGUI_ADDONS -DRMT_ENABLED=0 -DRMT_USE_D3D11=0 -DRMT_USE_OPENGL=0 -DUSING_GENERATED_CONFIG_H -DYES_IMGUIDOCK -DYES_IMGUIHELPER -DYES_IMGUIPANELMANAGER -DYES_IMGUITABWINDOW -DYES_IMGUITOOLBAR -D_GNU_SOURCE -I/usr/include/gtk-2.0 -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -Isubmodules/SDL/include -I/usr/include/x86_64-linux-gnu -I../../src/beeb/include -I../../src/shared/h -I../../src/6502/h -I../../submodules/salieri -I../../submodules/miniz -I../../submodules/Remotery/lib -I../../submodules/imgui -I../../submodules/imgui_club/imgui_memory_editor -I../../submodules/rapidjson/include -I../../submodules/IconFontCppHeaders -I../../src/dear_imgui_hex_editor/. -I../../submodules/libuv/include -I../../submodules/http-parser -save-temps=obj -O2 -g -DNDEBUG   -Wall -Wuninitialized -Winit-self -pedantic -Werror=implicit-function-declaration -Wsign-conversion -Wunused-result -Wno-overlength-strings -Wunused-parameter -std=gnu++14 -MD -MT src/b2/CMakeFiles/b2.dir/roms.cpp.o -MF src/b2/CMakeFiles/b2.dir/roms.cpp.o.d -o src/b2/CMakeFiles/b2.dir/roms.cpp.o -c ../../src/b2/roms.cpp
cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++
cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++
In file included from ../../src/b2/roms.cpp:3:0:
../../src/b2/roms.h:29:14: error: ‘array’ in namespace ‘std’ does not name a template type
 typedef std::array<uint8_t,ROM_SIZE> BeebRomData;
```

Full log can be found at https://launchpadlibrarian.net/479700453/buildlog_snap_ubuntu_bionic_amd64_838800541b00da327b76d143b95630b6_BUILDING.txt.gz

The config I'm using to build is at https://github.com/popey/b2-snap/blob/master/snap/snapcraft.yaml#L69

Any ideas why this may now be failing? Did your compiler / toolchain requirements change in the last 30 days perhaps? 

Steps to reproduce.

On a linux system with snap support.
`snap install snapcraft --classic`
`snap install multipass --classic`
Clone https://github.com/popey/b2-snap/
in `b2-snap` folder, run `snapcraft`
This should spin up an Ubuntu 18.04 VM using multipass and build inside it.

Alternatively if you've got an Ubuntu 18.04 system already in a VM (and thus don't want or need to nest VMs inside) you can, inside that VM:

`snap install snapcraft --classic`
Clone https://github.com/popey/b2-snap/
in `b2-snap` folder, run `snapcraft --destructive-mode` (this is to say it will build in the VM you already stood up).
This should spin up an Ubuntu 18.04 VM using multipass and build inside it.

**Comment by tom-seddon** [comment]
Thanks for the report - I bet this is due to me merging into master last week. My Linux PC had to make way for some work stuff, so testing on that must have slipped my mind. Apologies!

I'm going to look at fixing this now.

Thanks,

--Tom

**Comment by tom-seddon** [comment]
Hopefully fixed by https://github.com/tom-seddon/b2/commit/c525a34714b9305e77842de976992c0d1f230c9f - the snap file seems to have built on my Linux PC OK. I can't actually run it currently, as I've got no display for it... I just did this over ssh!

I did have to run all the snap commands via sudo, as prompted - is this as expected?

Linux version is `Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-70-generic x86_64)`. Actual PC, rather than a VM.

Thanks,

--Tom

**Comment by tom-seddon** [comment]
Just thought to do a google search, and I found https://snapcraft.io/b2 - nice! I'll put a link in the docs, and I'll try to test this config more often in future.

The snap is going to have to remain unsupported by me, I'm afraid, as I don't know enough about Linux to be useful. But I should put more effort into at least not breaking it.

Thanks,

--Tom

**Comment by tom-seddon** [comment]
Going by #109, I'm assuming it's all working again now? - I have a quick skim through my b2 bugs every couple of weeks, so I'll close this next time I do that if I don't hear otherwise.

Thanks,

--Tom

**Comment by popey** [comment]
Yes, all working now.
